on: pull_request
name: CI
jobs:
  linter:
    name: PHP CodeSniffer / CS Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: php-cs-fixer

      - name: PHP CS Fixer
        run: php-cs-fixer fix --config=.php-cs-fixer.php --using-cache=no --verbose --dry-run