on: pull_request
name: CI
jobs:
  linter:
    name: PHP CodeSniffer / CS Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs --using-cache=no --verbose --dry-run
      - name: PHP_CodeSniffer
        uses: chekalsky/phpcs-action@v1